<a href="https://colab.research.google.com/github/bharath5293/data-handling/blob/main/numpy_basic_operations.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import numpy as np

In [7]:
array_1d = np.array([1, 2, 3, 4, 5])
array_2d = np.array([[1, 2, 3], [4, 5, 6]])
array_3d = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print("Shape:", array_1d.shape)
print("Size:", array_1d.size)
print("Shape:", array_2d.shape)
print("Size:", array_2d.size)
print("Shape:", array_3d.shape)
print("Size:", array_3d.size)


Shape: (5,)
Size: 5
Shape: (2, 3)
Size: 6
Shape: (2, 2, 2)
Size: 8


In [8]:
array_2d = np.random.randint(0, 10, size=(3, 3))
print("2D Array:")
print(array_2d)
array_arranged = np.sort(array_2d, axis=None)
print("\nArranged Array:")
print(array_arranged)
array_random = np.random.rand(3, 3)
print("\nRandom Array:")
print(array_random)
array_linespace = np.linspace(1, 10, num=5)
print("\nLinespace Array:")
print(array_linespace)
array_ones = np.ones((4, 4))
print("\nOnes Array:")
print(array_ones)
array_zeros = np.zeros((2, 2))
print("\nZeros Array:")
print(array_zeros)
diagonal_elements = np.diag(array_2d)
print("\nDiagonal Elements:")
print(diagonal_elements)
array_sum = np.sum(array_2d)
print("\nSum of Array:")
print(array_sum)
array_min = np.min(array_2d)
print("\nMinimum Value:")
print(array_min)
array_max = np.max(array_2d)
print("\nMaximum Value:")
print(array_max)
array_mean = np.mean(array_2d)
print("\nMean of Array:")
print(array_mean)

2D Array:
[[9 8 6]
 [2 0 6]
 [0 6 8]]

Arranged Array:
[0 0 2 6 6 6 8 8 9]

Random Array:
[[0.80677793 0.14358966 0.98647833]
 [0.32732365 0.82731154 0.46377319]
 [0.30687479 0.47513533 0.81090976]]

Linespace Array:
[ 1.    3.25  5.5   7.75 10.  ]

Ones Array:
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]

Zeros Array:
[[0. 0.]
 [0. 0.]]

Diagonal Elements:
[9 0 8]

Sum of Array:
45

Minimum Value:
0

Maximum Value:
9

Mean of Array:
5.0


In [9]:
student_marks = np.random.randint(0, 101, size=50)
passed_marks = student_marks[student_marks >= 30]
failed_marks = student_marks[student_marks < 30]
num_passed = len(passed_marks)
num_failed = len(failed_marks)
print("Total number of students:", len(student_marks))
print("Number of students who passed:", num_passed)
print("Number of students who failed:", num_failed)
print("\nMarks of students who failed:")
print(failed_marks)

Total number of students: 50
Number of students who passed: 34
Number of students who failed: 16

Marks of students who failed:
[18 25 24  0 23 13 27 22 27 21  1 12 16 13 13 16]


In [10]:
array_2d = np.random.randint(1, 51, size=(5, 5))

print(array_2d)

[[ 5 50  3 44  7]
 [10  5 27 10 16]
 [30  1 40  3 35]
 [39 12  4 14 46]
 [ 5  2 12  1 13]]


In [11]:
array_odd = np.arange(-29, 11, step=2)

print(array_odd)

[-29 -27 -25 -23 -21 -19 -17 -15 -13 -11  -9  -7  -5  -3  -1   1   3   5
   7   9]
